name: 'Promtool Check Action'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'prometheus/rules/*.yml'
jobs:
  promtool:
    name: 'Promtool'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Promtool Check'
        uses: karancode/promtool-action@init
        with:
          prom_version: '2.9.2'      
          prom_check_subcommand: 'rules'
          prom_check_files: './prometheus/rules/*.yml'
          prom_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      